[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rosetta_runtime"
version = "2.0.0"
requires-python = ">= 3.10"
dependencies = [
   "pydantic>=2.6.1"
]

[tool.setuptools.packages.find]
where = ["src"]